export default [
  /* TEJ */ "ASKUMAR",
  /* TEJ */ "MEISTER",
  /* TEJ */ "MAN",
  /* TEJ */ "ERINO",
  /* TEJ */ "IKISTAN",
  /* TEJ */ "ANITOR",
  /* TEJ */ "UICE",
  /* TEJ */ "U",
  /* TEJ */ "AREDPALMER",
  /* TEJ */ "AX",
  /* TEJ */ "ASCRIPT",
  /* TEJ */ "स कुमार",
  /* TEJ */ "ANIEVÄKALLIO",
  /* TEJ */ "AVASCRIPT",
  /* TEJ */ "À-VU",
  /* TEJ */ "OMIZER",
  /* TEJ */ "ACKINTHEBOX",
  /* TEJ */ "ACKNICHOLSON",
  /* TEJ */ "ACKSONFAMILY",
  /* TEJ */ "ACKSONPOLLOCK",
  /* TEJ */ "ASONMOMOA",
  /* TEJ */ "AZZMATAZZ",
  /* TEJ */ "ESUSANDMARYCHAIN",
  /* TEJ */ "OLLYROGER"
];
